### ISSUE TITLE
[BUG][COMPAT?] Errors collecting metrics since update of routerOS to 7.18.1

### ISSUE THREAD

**Issue by Byh0ki** [akpw/mktxp#234]
Hello,

First of all, thank you and all the contributors for this awesome project, it helps a lot to get info on what is happening on the router 😄 

Since I've upgraded to `7.18.1`, it have a lot of `'Malformed sentence %s', [b'!empty', b'.tag=311844']` errors in the logs. Here is a little extract:

```
Error getting Neighbors info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311751'])
Error getting Neighbors info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311752'])
Error getting IPv6 firewall filters info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311766'])
Error getting IPv6 firewall filters info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311767'])
Error getting IPv6 firewall filters info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311768'])
Error getting Netwatch info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311780'])
Error getting system resource info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311784'])
Error getting system resource info from router mkt@192.168.88.1: ('Malformed sentence %s', [b'!empty', b'.tag=311785'])
```

Let me know if you need anything else to find the source of the issue

**Comment by Byh0ki** [comment]
Might be related to https://github.com/akpw/mktxp/issues/224?

**Comment by akpw** [comment]
this is related to #229. The problem should be fixed in the latest release, feel free to re-open if still there after the upgrade.

**Comment by dginhoux** [comment]
Hi,

Good news!
I hope 1.2.11 coming soon.
thank you for your work

**Comment by ventra007** [comment]
Hi,

MKTXP version 1.2.10
ROS version 7.18.2

Just as an FYI, still receiving malformed errors:

`mktxp  | Error getting IPv4 firewall filters info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])
mktxp  | Error getting Netwatch info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])
mktxp  | Error getting wireless interface monitor info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])
mktxp  | Error getting wireless registration table info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])
mktxp  | Error getting CAPsMAN remote caps info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])
mktxp  | Error getting CAPsMAN registration table info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])
mktxp  | Error getting CAPsMAN interfaces info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])
mktxp  | Error getting system resource info from router xxxx: ('Malformed sentence %s', [b'!empty', b'.tag=XXX'])`

Many thanks

**Comment by akpw** [comment]
can you check on the library version? e.g., `pip list | grep RouterOS-api`

**Comment by ventra007** [comment]
RouterOS-api - 0.18.1

**Comment by ventra007** [comment]
Hello. Any update regarding this? Is it also possible to reopen this issue?

**Comment by akpw** [comment]
thought this was resolved? you still have the old version of the library, while [mktxp setup](https://github.com/akpw/mktxp/blob/main/setup.py) requires a newer version:
```
    install_requires = ['prometheus-client>=0.9.0', 
                        'RouterOS-api>=0.19.0',
                        ...
```

So just install the latest mktxp, if that does not update the library for whatever reason you can do it with pip ' pip install RouterOS-api --upgrade'

**Comment by fengmikaelson** [comment]
saw your issue too late

i update to 1.2.10

then i have the same question as you , i thought my fault always ,and i reinstall it and config it all the time ....

**Comment by ventra007** [comment]
Hi,

Instead of manually going into the docker exec and doing an upgrade, i just did a `docker compose pull` to get all new images which resolved the issue.
